/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimeComponent: typeof import('./components/AnimeComponent.vue')['default']
    AppBarComponent: typeof import('./components/AppBarComponent.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    CadastroComponent: typeof import('./components/CadastroComponent.vue')['default']
    ChatView: typeof import('./components/ChatView.vue')['default']
    EditarPerfilComponent: typeof import('./components/EditarPerfilComponent.vue')['default']
    EditarPerfilFotoComponent: typeof import('./components/EditarPerfilFotoComponent.vue')['default']
    FooterComponent: typeof import('./components/FooterComponent.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginComponent: typeof import('./components/LoginComponent.vue')['default']
    MainHomePage: typeof import('./pages/MainHomePage.vue')['default']
    PerfilUserComponent: typeof import('./components/PerfilUserComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
